/*
 * Copyright 2021-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.persistence.table_per_aggregate_type;

import dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.eventstream.*;
import dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.persistence.*;
import dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.serializer.*;
import dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.serializer.TenantSerializer.*;
import dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.serializer.json.*;
import dk.cloudcreate.essentials.components.foundation.postgresql.PostgresqlUtil;
import dk.cloudcreate.essentials.components.foundation.types.*;

import java.util.Objects;

import static dk.cloudcreate.essentials.shared.FailFast.requireNonNull;

/**
 * Configuration for the persistence of an {@link AggregateEventStream} belonging to a given {@link AggregateType}<br>
 * <u><b>Security related to {@code SeparateTablePerAggregateEventStreamConfiguration}:</b></u>
 * The {@link SeparateTablePerAggregateEventStreamConfiguration}'s contains the configuration for the persistence of an {@link AggregateEventStream} belonging to a given {@link AggregateType}<br>
 * <br>
 * <u>#eventStreamTableName</u><br>
 * The {@link SeparateTablePerAggregateEventStreamConfiguration#eventStreamTableName} defines the Postgresql table name where {@link PersistedEvent}'s related to {@link SeparateTablePerAggregateEventStreamConfiguration#aggregateType} are stored<br>
 * The {@code eventStreamTableName}'s value will be directly used in constructing SQL statements (in components using the {@link SeparateTablePerAggregateEventStreamConfiguration},
 * such as {@link SeparateTablePerAggregateTypePersistenceStrategy}) through string concatenation, which exposes the component to SQL injection attacks.<br>
 * <br>
 * <blockquote>It is the responsibility of the user of this component to sanitize the {@code eventStreamTableName}'s value
 * to ensure the security of all the SQL statements generated by components using the {@link SeparateTablePerAggregateEventStreamConfiguration}, such as the {@link SeparateTablePerAggregateTypePersistenceStrategy}.
 * </blockquote>
 * The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
 * call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
 * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
 * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
 * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
 * Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
 * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
 * <br>
 * It is highly recommended that the {@code eventStreamTableName}'s value is only derived from a controlled and trusted source.<br>
 * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code eventStreamTableName}'s value.<br>
 * <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
 * vulnerabilities, compromising the security and integrity of the database.</b><br>
 * <br>
 * <u>#eventStreamTableColumnNames</u><br>
 * The {@link SeparateTablePerAggregateEventStreamConfiguration#eventStreamTableColumnNames} defines the columns names used for persisting AggregateEventStreams related to a specific {@link AggregateType}<br>
 * <br>
 * <b>All the column names provided</b> will be directly used in constructing SQL statements
 * through string concatenation, in components such as {@link SeparateTablePerAggregateTypePersistenceStrategy}, which exposes those components to SQL injection attacks.<br>
 * <br>
 * <blockquote>It is the responsibility of the user of this component to sanitize <b>all the column names provided</b>
 * to ensure the security of all the SQL statements generated by this component.</blockquote><br>
 * The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
 * call the {@link EventStreamTableColumnNames#validate()} method, which uses {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)}, to validate the column names provided as a first line of defense.<br>
 * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
 * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
 * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
 * Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
 * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
 * <br>
 * It is highly recommended that <b>all the column names provided</b> are derived from a controlled and trusted source.<br>
 * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the column name values.<br>
 * <b>Failure to adequately sanitize and validate these values could expose the application to SQL injection
 * vulnerabilities, compromising the security and integrity of the database.</b><br>
 * <br>
 * <u>AggregateType</u><br>
 * The {@code aggregateType}'s value will be converted to a table name, or part of a table name, in {@link SeparateTablePerAggregateTypePersistenceStrategy},
 * and thereafter directly be used in constructing SQL statements through string concatenation, which exposes that component to SQL injection attacks.<br>
 * <br>
 * It is the responsibility of the user of this component to sanitize the {@code aggregateType}'s value
 * to ensure the security of all the SQL statements generated by this component. The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
 * call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
 * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
 * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
 * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
 * Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
 * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
 *
 * <br>
 * It is highly recommended that the {@code aggregateType}'s value is only derived from a controlled and trusted source.<br>
 * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code aggregateType}'s value.<br>
 * <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
 */
public final class SeparateTablePerAggregateEventStreamConfiguration extends AggregateEventStreamConfiguration {
    /**
     * The unique name of the Postgresql table name where ONLY {@link PersistedEvent}'s related to {@link #aggregateType} are stored<br>
     * <b>Note: The table name provided will automatically be converted to <u>lower case</u></b>
     */
    public final String                      eventStreamTableName;
    /**
     * The names of the {@link #eventStreamTableName} columns - The actual implementation must be compatible with the chosen {@link AggregateEventStreamPersistenceStrategy}
     */
    public final EventStreamTableColumnNames eventStreamTableColumnNames;

    /**
     * @param aggregateType               The type of Aggregate this event stream configuration relates to<br>
     *                                    <strong>Note:</strong><br>
     *                                    The {@code aggregateType}'s value will be converted to a table name, or part of a table name, in {@link SeparateTablePerAggregateTypePersistenceStrategy},
     *                                    and thereafter directly be used in constructing SQL statements through string concatenation, which exposes that component to SQL injection attacks.<br>
     *                                    <br>
     *                                    <strong>Security Note:</strong><br>
     *                                    It is the responsibility of the user of this component to sanitize the {@code aggregateType}'s value
     *                                    to ensure the security of all the SQL statements generated by this component. The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
     *                                    call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                                    The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                    However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                    <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     *                                    Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
     *                                    Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *
     *                                    <br>
     *                                    It is highly recommended that the {@code aggregateType}'s value is only derived from a controlled and trusted source.<br>
     *                                    To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code aggregateType}'s value.<br>
     *                                    <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     * @param eventStreamTableName        The unique name of the Postgresql table name where ONLY {@link PersistedEvent}'s related to {@link #aggregateType} are stored<br>
     *                                    <b>Note: The table name provided will automatically be converted to <u>lower case</u></b><br>
     *                                    <br>
     *                                    <strong>Note:</strong><br>
     *                                    The {@code eventStreamTableName}'s value will be directly used in constructing SQL statements (in components using the {@link SeparateTablePerAggregateEventStreamConfiguration},
     *                                    such as {@link SeparateTablePerAggregateTypePersistenceStrategy}) through string concatenation, which exposes the component to SQL injection attacks.<br>
     *                                    <br>
     *                                    <strong>Security Note:</strong><br>
     *                                    <b>It is the responsibility of the user of this component to sanitize the {@code eventStreamTableName}'s value
     *                                    to ensure the security of all the SQL statements generated by components using the {@link SeparateTablePerAggregateEventStreamConfiguration}, such as the
     *                                    {@link SeparateTablePerAggregateTypePersistenceStrategy}.</b><br>
     *                                    <br>
     *                                    The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
     *                                    call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                                    The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                    However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                    <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     *                                    Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
     *                                    Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *                                    <br>
     *                                    It is highly recommended that the {@code eventStreamTableName}'s value is only derived from a controlled and trusted source.<br>
     *                                    To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code eventStreamTableName}'s value.<br>
     *                                    <br>
     *                                    <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                                    vulnerabilities, compromising the security and integrity of the database.</b>
     * @param eventStreamTableColumnNames The names of the {@link #eventStreamTableName} columns - The actual implementation must be compatible with the chosen {@link AggregateEventStreamPersistenceStrategy}<br>
     *                                    <br>
     *                                    <u><b>Security</b></u><br>
     *                                    <br>
     *                                    <b>All the column names provided</b> will be directly used in constructing SQL statements
     *                                    through string concatenation, in components such as {@link SeparateTablePerAggregateTypePersistenceStrategy}, which exposes those components to SQL injection attacks.<br>
     *                                    <br>
     *                                    It is the responsibility of the user of this component to sanitize <b>all the column names provided</b>
     *                                    to ensure the security of all the SQL statements generated by this component. The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
     *                                    call the {@link EventStreamTableColumnNames#validate()} method, which uses {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)}, to validate the column names provided as a first line of defense.<br>
     *                                    The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                    However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                    <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     *                                    Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
     *                                    Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *                                    <br>
     *                                    It is highly recommended that <b>all the column names provided</b> are derived from a controlled and trusted source.<br>
     *                                    To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the column name values.<br>
     *                                    <br>
     *                                    <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                                    vulnerabilities, compromising the security and integrity of the database.</b>
     * @param queryFetchSize              The SQL fetch size for Queries
     * @param jsonSerializer              The {@link JSONEventSerializer} used to serialize and deserialize {@link PersistedEvent#event()} and {@link PersistedEvent#metaData()}
     * @param aggregateIdSerializer       The serializer for the Aggregate Id
     * @param aggregateIdColumnType       The SQL Column type for the Aggregate Id<br>
     *                                    We've deliberately split {@link AggregateIdSerializer} and {@link #aggregateIdColumnType}
     *                                    as it's possible to use e.g. a {@link AggregateIdSerializer.StringIdSerializer} or {@link AggregateIdSerializer.CharSequenceTypeIdSerializer}
     *                                    which purely contains {@link java.util.UUID} string values, in which case it should be possible to
     *                                    map these to {@link IdentifierColumnType#UUID}
     * @param eventIdColumnType           The SQL column type for the {@link EventId} column
     * @param correlationIdColumnType     The SQL column type for the {@link CorrelationId} column
     * @param eventJsonColumnType         The SQL column type for the {@link JSONEventSerializer} serialized Event
     * @param eventMetadataJsonColumnType The SQL column type for the {@link JSONEventSerializer} serialized {@link EventMetaData}
     * @param tenantSerializer            The serializer for the {@link Tenant} value (or {@link NoSupportForMultiTenancySerializer} if it's a single tenant application)
     */
    public SeparateTablePerAggregateEventStreamConfiguration(AggregateType aggregateType,
                                                             String eventStreamTableName,
                                                             EventStreamTableColumnNames eventStreamTableColumnNames,
                                                             int queryFetchSize,
                                                             JSONEventSerializer jsonSerializer,
                                                             AggregateIdSerializer aggregateIdSerializer,
                                                             IdentifierColumnType aggregateIdColumnType,
                                                             IdentifierColumnType eventIdColumnType,
                                                             IdentifierColumnType correlationIdColumnType,
                                                             JSONColumnType eventJsonColumnType,
                                                             JSONColumnType eventMetadataJsonColumnType,
                                                             TenantSerializer<?> tenantSerializer) {
        super(aggregateType,
              queryFetchSize,
              jsonSerializer,
              aggregateIdSerializer,
              aggregateIdColumnType,
              eventIdColumnType,
              correlationIdColumnType,
              eventJsonColumnType,
              eventMetadataJsonColumnType,
              tenantSerializer);
        this.eventStreamTableName = requireNonNull(eventStreamTableName, "No eventStreamTableName provided").toLowerCase();
        this.eventStreamTableColumnNames = requireNonNull(eventStreamTableColumnNames, "No eventStreamTableColumnNames provided");

        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventStreamTableName);
        this.eventStreamTableColumnNames.validate();
    }

    /**
     * Create an event stream configuration for the given aggregate type using common configuration:<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#eventStreamTableName} = {@link AggregateType#toString()} + "_events<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#eventStreamTableColumnNames} = {@link EventStreamTableColumnNames#defaultColumnNames()}<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#queryFetchSize} = 100<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#tenantSerializer} = {@link NoSupportForMultiTenancySerializer}<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#jsonSerializer} = {@link JacksonJSONEventSerializer}<br>
     *
     * @param aggregateType                             The type of Aggregate this event stream configuration relates to<br>
     *                                                  <strong>Note:</strong><br>
     *                                                  The {@code aggregateType}'s value will be converted to a table name, or part of a table name, in {@link SeparateTablePerAggregateTypePersistenceStrategy},
     *                                                  and thereafter directly be used in constructing SQL statements through string concatenation, which exposes that component to SQL injection attacks.<br>
     *                                                  <br>
     *                                                  <strong>Security Note:</strong><br>
     *                                                  It is the responsibility of the user of this component to sanitize the {@code aggregateType}'s value
     *                                                  to ensure the security of all the SQL statements generated by this component. The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
     *                                                  call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                                                  The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                                  However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                                  <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     *                                                  Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
     *                                                  Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *
     *                                                  <br>
     *                                                  It is highly recommended that the {@code aggregateType}'s value is only derived from a controlled and trusted source.<br>
     *                                                  To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code aggregateType}'s value.<br>
     *                                                  <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     * @param jsonSerializer                            The {@link JSONEventSerializer}
     * @param aggregateIdSerializer                     The serializer for the Aggregate Id
     * @param identifierColumnTypeUsedForAllIdentifiers The SQL Column type used for all identifier columns (aggregate id, event id, correlation id, etc.)
     * @param jsonColumnTypeUsedForAllJSONColumns       The SQL JSON column type used for all JSON columns (Event and {@link EventMetaData})
     * @return the event stream configuration for the given aggregate type
     */
    public static SeparateTablePerAggregateEventStreamConfiguration standardSingleTenantConfiguration(AggregateType aggregateType,
                                                                                                      JSONEventSerializer jsonSerializer,
                                                                                                      AggregateIdSerializer aggregateIdSerializer,
                                                                                                      IdentifierColumnType identifierColumnTypeUsedForAllIdentifiers,
                                                                                                      JSONColumnType jsonColumnTypeUsedForAllJSONColumns) {
        return standardConfiguration(aggregateType,
                                     jsonSerializer,
                                     aggregateIdSerializer,
                                     identifierColumnTypeUsedForAllIdentifiers,
                                     jsonColumnTypeUsedForAllJSONColumns,
                                     new NoSupportForMultiTenancySerializer());
    }

    /**
     * Create an event stream configuration for the given aggregate type using common configuration:<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#eventStreamTableName} = {@link AggregateType#toString()} + "_events<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#eventStreamTableColumnNames} = {@link EventStreamTableColumnNames#defaultColumnNames()}<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#queryFetchSize} = 100<br>
     * {@link SeparateTablePerAggregateEventStreamConfiguration#jsonSerializer} = {@link JacksonJSONEventSerializer}<br>
     *
     * @param aggregateType                             The type of Aggregate this event stream configuration relates to
     *                                                  <br>
     *                                                  <strong>Note:</strong><br>
     *                                                  The {@code aggregateType}'s value will be converted to a table name, or part of a table name, in {@link SeparateTablePerAggregateTypePersistenceStrategy},
     *                                                  and thereafter directly be used in constructing SQL statements through string concatenation, which exposes that component to SQL injection attacks.<br>
     *                                                  <br>
     *                                                  <strong>Security Note:</strong><br>
     *                                                  It is the responsibility of the user of this component to sanitize the {@code aggregateType}'s value
     *                                                  to ensure the security of all the SQL statements generated by this component. The {@link SeparateTablePerAggregateEventStreamConfiguration} component will
     *                                                  call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                                                  The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                                  However, {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                                  <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     *                                                  Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
     *                                                  Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *
     *                                                  <br>
     *                                                  It is highly recommended that the {@code aggregateType}'s value is only derived from a controlled and trusted source.<br>
     *                                                  To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code aggregateType}'s value.<br>
     *                                                  <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                                                  vulnerabilities, compromising the security and integrity of the database.</b>
     * @param jsonSerializer                            The {@link JSONEventSerializer}
     * @param aggregateIdSerializer                     The serializer for the Aggregate Id
     * @param identifierColumnTypeUsedForAllIdentifiers The SQL Column type used for all identifier columns (aggregate id, event id, correlation id, etc.)
     * @param jsonColumnTypeUsedForAllJSONColumns       The SQL JSON column type used for all JSON columns (Event and {@link EventMetaData})
     * @param tenantSerializer                          The {@link TenantSerializer} to use (e.g. {@link TenantIdSerializer})
     * @return the event stream configuration for the given aggregate type
     */
    public static SeparateTablePerAggregateEventStreamConfiguration standardConfiguration(AggregateType aggregateType,
                                                                                          JSONEventSerializer jsonSerializer,
                                                                                          AggregateIdSerializer aggregateIdSerializer,
                                                                                          IdentifierColumnType identifierColumnTypeUsedForAllIdentifiers,
                                                                                          JSONColumnType jsonColumnTypeUsedForAllJSONColumns,
                                                                                          TenantSerializer<?> tenantSerializer) {
        requireNonNull(aggregateType, "No aggregateType provided");
        PostgresqlUtil.checkIsValidTableOrColumnName(aggregateType.toString());
        return new SeparateTablePerAggregateEventStreamConfiguration(aggregateType,
                                                                     aggregateType.toString() + "_events",
                                                                     EventStreamTableColumnNames.defaultColumnNames(),
                                                                     100,
                                                                     jsonSerializer,
                                                                     aggregateIdSerializer,
                                                                     identifierColumnTypeUsedForAllIdentifiers,
                                                                     identifierColumnTypeUsedForAllIdentifiers,
                                                                     identifierColumnTypeUsedForAllIdentifiers,
                                                                     jsonColumnTypeUsedForAllJSONColumns,
                                                                     jsonColumnTypeUsedForAllJSONColumns,
                                                                     tenantSerializer);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SeparateTablePerAggregateEventStreamConfiguration)) return false;
        SeparateTablePerAggregateEventStreamConfiguration that = (SeparateTablePerAggregateEventStreamConfiguration) o;
        return aggregateType.equals(that.aggregateType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(aggregateType);
    }

    @Override
    public String toString() {
        return "SeparateTablePerAggregateEventStreamConfiguration{" +
                "eventStreamTableName='" + eventStreamTableName + '\'' +
                ", eventStreamTableColumnNames=" + eventStreamTableColumnNames +
                ", aggregateType=" + aggregateType +
                ", queryFetchSize=" + queryFetchSize +
                ", jsonSerializer=" + jsonSerializer +
                ", aggregateIdSerializer=" + aggregateIdSerializer +
                ", aggregateIdColumnType=" + aggregateIdColumnType +
                ", eventIdColumnType=" + eventIdColumnType +
                ", correlationIdColumnType=" + correlationIdColumnType +
                ", eventJsonColumnType=" + eventJsonColumnType +
                ", eventMetadataJsonColumnType=" + eventMetadataJsonColumnType +
                ", tenantSerializer=" + tenantSerializer +
                '}';
    }
}
