/*
 * Copyright 2021-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.eventstream;


import dk.cloudcreate.essentials.components.eventsourced.eventstore.postgresql.EventStore;
import dk.cloudcreate.essentials.components.foundation.postgresql.PostgresqlUtil;
import dk.cloudcreate.essentials.components.foundation.types.Tenant;

import static dk.cloudcreate.essentials.shared.FailFast.requireNonNull;

/**
 * Builder for the {@link EventStreamTableColumnNames} type<br>
 * <br>
 * <u><b>Security</b></u><br>
 * <br>
 * <b>All the column names provided</b> will be directly used in constructing SQL statements
 * through string concatenation, which exposes the component to SQL injection attacks.<br>
 * <br>
 * <b>It is the responsibility of the user of this component to sanitize <b>all the column names provided</b>
 * to ensure the security of all the SQL statements generated by this component.</b>
 * <p>
 * The {@link EventStreamTableColumnNames} component will
 * call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the column names provided as a first line of defense.<br>
 * <br>
 * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
 * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
 * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
 * Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
 * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
 * <br>
 * It is highly recommended that <b>all the column names provided</b> are derived from a controlled and trusted source.<br>
 * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the column name values.<br>
 * <br>
 * <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
 * vulnerabilities, compromising the security and integrity of the database.</b>
 */
public final class EventStreamTableColumnNamesBuilder {
    private String globalOrderColumn;
    private String timestampColumn;
    private String eventIdColumn;
    private String aggregateIdColumn;
    private String eventOrderColumn;
    private String eventTypeColumn;
    private String eventRevisionColumn;
    private String eventPayloadColumn;
    private String eventMetaDataColumn;
    private String causedByEventIdColumn;
    private String correlationIdColumn;
    private String tenantColumn;

    /**
     * The name of the column that contains the global order of an event<br>
     * Contains the global order an event<br>
     * The Global Order is a sequential ever-growing number, which that tracks the order in which events have been stored in the {@link EventStore} table
     * across all {@link AggregateEventStream}'s with the same {@link AggregateType}.<br>
     * The first global-event-order has value 1, since this is the initial value for a Postgresql BIGINT IDENTITY column.
     *
     * @param globalOrderColumn The name of the column that contains the global order of an event<br>
     *                          <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                          lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder globalOrderColumn(String globalOrderColumn) {
        this.globalOrderColumn = requireNonNull(globalOrderColumn, "You must supply a globalOrderColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.globalOrderColumn);
        return this;
    }

    /**
     * The name of the column that contains the timestamp of an event
     *
     * @param timestampColumn The name of the column that contains the timestamp of an event<br>
     *                        <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                        lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder timestampColumn(String timestampColumn) {
        this.timestampColumn = requireNonNull(timestampColumn, "You must supply a timestampColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.timestampColumn);
        return this;
    }

    /**
     * The name of the column that contains the identifier of an event
     *
     * @param eventIdColumn The name of the column that contains the identifier of an event<br>
     *                      <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                      lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder eventIdColumn(String eventIdColumn) {
        this.eventIdColumn = requireNonNull(eventIdColumn, "You must supply a eventIdColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventIdColumn);
        return this;
    }

    /**
     * The name of the column that contains the identifier of the event that caused the Event stored in the row to occur
     *
     * @param causedByEventIdColumn The name of the column that contains the identifier of the event that caused the Event stored in the row to occur<br>
     *                              <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                              lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder causedByEventIdColumn(String causedByEventIdColumn) {
        this.causedByEventIdColumn = requireNonNull(causedByEventIdColumn, "You must supply a causedByEventIdColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.causedByEventIdColumn);
        return this;
    }

    /**
     * The name of the column that contains the aggregate identifier that an event is related to
     *
     * @param aggregateIdColumn The name of the column that contains the aggregate identifier that an event is related to<br>
     *                          <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                          lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder aggregateIdColumn(String aggregateIdColumn) {
        this.aggregateIdColumn = requireNonNull(aggregateIdColumn, "You must supply a aggregateIdColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.aggregateIdColumn);
        return this;
    }

    /**
     * The name of the column that contains the order of an event relative to the aggregate instance (the {@link #aggregateIdColumn})<br>
     * Each event has its own unique position within the stream, also known as the event-order,
     * which defines the order, in which the events were added to the aggregates {@link AggregateEventStream}<br>
     * <br>
     * The first eventOrder should have value 0 - but ultimately it's a decision of the developer.<br>
     * This is also commonly called the version or sequenceNumber, and it's a sequential ever-growing number.<br>
     * related to a <b>specific</b> aggregate instance (as opposed to the {@link #globalOrderColumn} which contains
     * the order of ALL events related to a specific {@link AggregateType})
     *
     * @param eventOrderColumn The name of the column that contains the order of an event relative to the aggregate instance (the {@link #aggregateIdColumn})<br>
     *                         <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                         lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder eventOrderColumn(String eventOrderColumn) {
        this.eventOrderColumn = requireNonNull(eventOrderColumn, "You must supply a eventOrderColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventOrderColumn);
        return this;
    }

    /**
     * The name of the column contains the type of the event stored in the row<br>
     *
     * @param eventTypeColumn The name of the column contains the type of the event stored in the row<br>
     *                        <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                        lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder eventTypeColumn(String eventTypeColumn) {
        this.eventTypeColumn = requireNonNull(eventTypeColumn, "You must supply a eventTypeColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventTypeColumn);
        return this;
    }

    /**
     * The name of the column that contains the revision number of the serialized event
     *
     * @param eventRevisionColumn The name of the column that contains the revision number of the serialized event<br>
     *                            <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                            lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder eventRevisionColumn(String eventRevisionColumn) {
        this.eventRevisionColumn = requireNonNull(eventRevisionColumn, "You must supply a eventRevisionColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventRevisionColumn);
        return this;
    }

    /**
     * The name of the column that contains the JSON serialized event payload
     *
     * @param eventPayloadColumn The name of the column that contains the JSON serialized event payload<br>
     *                           <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                           lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder eventPayloadColumn(String eventPayloadColumn) {
        this.eventPayloadColumn = requireNonNull(eventPayloadColumn, "You must supply a eventPayloadColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventPayloadColumn);
        return this;
    }

    /**
     * The name of the column that contains the JSON serialized metadata of an event
     *
     * @param eventMetaDataColumn The name of the column that contains the JSON serialized metadata of an event<br>
     *                            <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                            lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder eventMetaDataColumn(String eventMetaDataColumn) {
        this.eventMetaDataColumn = requireNonNull(eventMetaDataColumn, "You must supply a eventMetaDataColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.eventMetaDataColumn);
        return this;
    }

    /**
     * The name of the column that contains the correlation identifier that links correlated events together
     *
     * @param correlationIdColumn The name of the column that contains the correlation identifier that links correlated events together<br>
     *                            <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                            lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder correlationIdColumn(String correlationIdColumn) {
        this.correlationIdColumn = requireNonNull(correlationIdColumn, "You must supply a correlationIdColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.correlationIdColumn);
        return this;
    }

    /**
     * The name of the column that will contain the {@link Tenant} (i.e. the tenant that the event belongs to)<br>
     * Having a {@link #tenantColumn} is mandatory, but having a {@link Tenant} value associated with an Event, through {@link PersistedEvent#tenant()} is optional.
     *
     * @param tenantColumn The name of the column that will contain the {@link Tenant} (i.e. the tenant that the event belongs to)<br>
     *                     <b>The responsibility to ensure sanitization and validation of the column name, to protect against SQL Injection attacks,
     *                     lies exclusively with the users/developers using this builder and the other {@link EventStore} components.</b>
     * @return this builder instance
     */
    public EventStreamTableColumnNamesBuilder tenantColumn(String tenantColumn) {
        this.tenantColumn = requireNonNull(tenantColumn, "You must supply a tenantColumn");
        PostgresqlUtil.checkIsValidTableOrColumnName(this.tenantColumn);
        return this;
    }

    /**
     * Convert the builder to an {@link EventStreamTableColumnNames} instance<br>
     * <b>Note: All column names provided will automatically be converted to <u>lower case</u></b><br>
     * <br>
     * <u><b>Security</b></u><br>
     * <br>
     * <b>All the column names provided</b> will be directly used in constructing SQL statements
     * through string concatenation, which exposes the component to SQL injection attacks.<br>
     * <br>
     * <b>It is the responsibility of the user of this component to sanitize <b>all the column names provided</b>
     * to ensure the security of all the SQL statements generated by this component.</b>
     * <p>
     * The {@link EventStreamTableColumnNames} component will
     * call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the column names provided as a first line of defense.<br>
     * <br>
     * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     * Users must ensure thorough sanitization and validation of API input parameters,  column, table, and index names.<br>
     * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     * <br>
     * It is highly recommended that <b>all the column names provided</b> are derived from a controlled and trusted source.<br>
     * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the column name values.<br>
     * <br>
     * <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     * vulnerabilities, compromising the security and integrity of the database.</b>
     *
     * @return an {@link EventStreamTableColumnNames} instance with all the builder values applied
     */
    public EventStreamTableColumnNames build() {
        return new EventStreamTableColumnNames(globalOrderColumn,
                                               timestampColumn,
                                               eventIdColumn,
                                               causedByEventIdColumn,
                                               correlationIdColumn,
                                               aggregateIdColumn,
                                               eventOrderColumn,
                                               eventTypeColumn,
                                               eventRevisionColumn,
                                               eventPayloadColumn,
                                               eventMetaDataColumn,
                                               tenantColumn);
    }
}